### ISSUE TITLE
Low publishing rate

### ISSUE THREAD

**Issue by almeidajp** [RIVeR-Lab/apriltags_ros#21]
I am using this package to identify some apriltags in a Gazebo Simulation. The simulation is publishing the camera image in 15 hz and the image size is 640 x 480.

The issue is that I am getting a 2 hz publishing rate from tag_detections and it is too low for my application.

I am running the gazebo simulation and the apriltags_ros in an Ubuntu 14.04 pure in a core i7 laptop with 8gb ram. Is that publishing rate normal? Does anyone know how to increase it?

**Comment by velinddimitrov** [comment]
Did you use the binary or build from source? If you build from source, FYI: https://answers.ros.org/question/71965/catkin-compiled-code-runs-3x-slower/
