### ISSUE TITLE
Does not detect 

### ISSUE THREAD

**Issue by dzt109** [RIVeR-Lab/apriltags_ros#27]
I have a situation where I have a calibrated camera that works properly on rosrun image_view. I show the camera the right kind of apriltags, there are no errors or warnings,  but no detections are reported.

detections : []

Not sure where the issue is. What would be the best steps to debug from here?

**Comment by velinddimitrov** [comment]
Do you have the tag you are looking for specified in the launch file?

**Comment by dzt109** [comment]
I did have the tag. Updating my linux distribution solved this problem.
