### ISSUE TITLE
I can't get "/tag_detections_pose" rate

### ISSUE THREAD

**Issue by PonTk-stack** [RIVeR-Lab/apriltags_ros#39]
I tried to command "rostopic echo /tag_detections_pose".
But Coordinates are not output.

header:
  seq: 1519
  stamp: 
    secs: 1558535045
    nsecs: 635062520
  frame_id: "camera"
poses: 
  - 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---

Please help me.

**Comment by drjerrysu** [comment]
I have the same problem
